from secrets import randbelow
from database_setup import Engine, LeagueOfLegendsProfileBase
from sqlalchemy.orm import sessionmaker, load_only

Session = sessionmaker(bind=Engine)
session = Session()


def generate_pass_code():
    return str(randbelow(999999))


def generate_username():
    right_side = [
        "Aatrox",
        "Ahri",
        "Akali",
        "Alistar",
        "Amumu",
        "Anivia",
        "Annie",
        "Ashe",
        "Aurelion Sol",
        "Azir",
        "Bard",
        "Blitzcrank",
        "Brand",
        "Braum",
        "Caitlyn",
        "Camille",
        "Cassiopeia",
        "Cho'Gath",
        "Corki",
        "Darius",
        "Diana",
        "Dr. Mundo",
        "Draven",
        "Ekko",
        "Elise",
        "Evelynn",
        "Ezreal",
        "Fiddlesticks",
        "Fiora",
        "Fizz",
        "Galio",
        "Gangplank",
        "Garen",
        "Gnar",
        "Gragas",
        "Graves",
        "Hecarim",
        "Heimerdinger",
        "Illaoi",
        "Irelia",
        "Ivern",
        "Janna",
        "Jarvan IV",
        "Jax",
        "Jayce",
        "Jhin",
        "Jinx",
        "Kai'Sa",
        "Kalista",
        "Karma",
        "Karthus",
        "Kassadin",
        "Katarina",
        "Kayle",
        "Kayn",
        "Kennen",
        "Kha'Zix",
        "Kindred",
        "Kled",
        "Kog'Maw",
        "LeBlanc",
        "Lee Sin",
        "Leona",
        "Lissandra",
        "Lucian",
        "Lulu",
        "Lux",
        "Malphite",
        "Malzahar",
        "Maokai",
        "Master Yi",
        "Miss Fortune",
        "Mordekaiser",
        "Morgana",
        "Nami",
        "Nasus",
        "Nautilus",
        "Nidalee",
        "Nocturne",
        "Nunu",
        "Olaf",
        "Orianna",
        "Ornn",
        "Pantheon",
        "Poppy",
        "Quinn",
        "Rakan",
        "Rammus",
        "Rek'Sai",
        "Renekton",
        "Rengar",
        "Riven",
        "Rumble",
        "Ryze",
        "Sejuani",
        "Shaco",
        "Shen",
        "Shyvana",
        "Singed",
        "Sion",
        "Sivir",
        "Skarner",
        "Sona",
        "Soraka",
        "Swain",
        "Syndra",
        "Tahm Kench",
        "Taliyah",
        "Talon",
        "Taric",
        "Teemo",
        "Thresh",
        "Tristana",
        "Trundle",
        "Tryndamere",
        "Twisted Fate",
        "Twitch",
        "Udyr",
        "Urgot",
        "Varus",
        "Vayne",
        "Veigar",
        "Vel'Koz",
        "Vi",
        "Viktor",
        "Vladimir",
        "Volibear",
        "Warwick",
        "Wukong",
        "Xayah",
        "Xerath",
        "Xin Zhao",
        "Yasuo",
        "Yorick",
        "Zac",
        "Zed",
        "Ziggs",
        "Zilean",
        "Zoe",
        "Zyra",
     ]

    left_side = [
        "PABLO",
        "GIOTTO",
        "LEONARDO",
        "PAUL",
        "REMBRANDT",
        "DIEGO",
        "WASSILY",
        "CLAUDE",
        "CARAVAGGIO",
        "JOSEPH",
        "JAN",
        "ALBRECHT",
        "JACKSON",
        "MICHELANGELO",
        "PAUL",
        "FRANCISCO",
        "VINCENT",
        "ÉDOUARD""MARK",
        "HENRI",
        "RAPHAEL",
        "JEAN",
        "EDVARD",
        "TITIAN",
        "PIET",
        "PIERO",
        "PETER",
        "ANDY",
        "JOAN",
        "TOMMASO",
        "MARC",
        "GUSTAVE",
        "NICOLAS",
        "WILLEM",
        "PAUL",
        "FRANCIS",
        "GUSTAV",
        "EUG",
        "PAOLO",
        "WILLIAM",
        "KAZIMIR",
        "ANDREA",
        "JAN",
        "EL",
        "CASPAR",
        "WINSLOW",
        "MARCEL",
        "GIORGIONE",
        "FRIDA",
        "HANS",
        "EDGAR",
        "FRA",
        "GEORGES",
        "JEAN",
        "SALVADOR",
        "MAX",
        "TINTORETTO",
        "JASPER",
        "SANDRO",
        "DAVID",
        "UMBERTO",
        "JOACHIM",
        "DUCCIO",
        "ROGER",
        "JOHN",
        "JACQUES",
        "ARSHILLE",
        "HIERONYMUS",
        "PIETER",
        "SIMONE",
        "Frederic",
        "EDWARD",
        "LUCIO",
        "FRANZ",
        "PIERRE",
        "JAMES",
        "THEODORE",
        "WILLIAM",
        "CAMILLE",
        "GEORGES",
        "HANS",
        "GERHARD",
        "AMEDEO",
        "GEORGES",
        "GENTILESCHI",
        "JEAN",
        "FRANCISCO",
        "CIMABUE",
        "JAMES",
        "REN",
        "EL",
        "EGON",
        "DANTE",
        "FRANS",
        "CLAUDE",
        "ROY",
        "GEORGIA",
        "GUSTAVE",
        "GIORGIO",
        "FERNAND",
        "JEAN"
    ]

    return right_side[randbelow(139)] + '_' + left_side[randbelow(100)]


def retrieve_user_mmr(summoner_id):
    user_mmr = session.\
        query(LeagueOfLegendsProfileBase).\
        filter_by(summoner_id=summoner_id).\
        options(load_only("mmr")).\
        first()
    return user_mmr
